
Setting up data pipeline
Restric
Virtual devices cannot be modified after being initialized
Epoch 1/2
2022-05-28 01:21:53.250331: I tensorflow/stream_executor/cuda/cuda_dnn.cc:366] Loaded cuDNN version 8400






      7/Unknown - 64s 8s/step - loss: 0.1318 - accuracy: 0.4437
Traceback (most recent call last):
  File "main.py", line 59, in <module>
    model_history = model.fit(
  File "/home/melih/anaconda3/envs/tf-web/lib/python3.8/site-packages/keras/utils/traceback_utils.py", line 67, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/home/melih/Code/uni/sem6/deep_cv/src/Callbacks/__init__.py", line 23, in on_epoch_end
    self.show_pred()
  File "/home/melih/Code/uni/sem6/deep_cv/src/Callbacks/__init__.py", line 30, in show_pred
    preds = self.model.predict(self.in_im)
AttributeError: 'DisplayTestCallback' object has no attribute 'in_im'