
Setting up data pipeline
[34m[1mwandb[39m[22m: [33mWARNING[39m The save_model argument by default saves the model in the HDF5 format that cannot save custom objects like subclassed models and custom layers. This behavior will be deprecated in a future release in favor of the SavedModel format. Meanwhile, the HDF5 model is saved as W&B files and the SavedModel as W&B Artifacts.
[34m[1mwandb[39m[22m: [33mWARNING[39m The data_type argument of wandb.keras.WandbCallback is deprecated and will be removed in a future release. Please use input_type instead.
[34m[1mwandb[39m[22m: [33mWARNING[39m Setting input_type = data_type.
Restric
Virtual devices cannot be modified after being initialized
Epoch 1/2
2022-06-01 12:48:24.342064: I tensorflow/stream_executor/cuda/cuda_dnn.cc:366] Loaded cuDNN version 8400
      1/Unknown - 21s 21s/step - loss: 0.2121 - accuracy: 0.6461
Traceback (most recent call last):
  File "main.py", line 66, in <module>
    model_history = model.fit(
  File "/home/melih/anaconda3/envs/tf-web/lib/python3.8/site-packages/wandb/integration/keras/keras.py", line 163, in new_v2
    return old_v2(*args, **kwargs)
  File "/home/melih/anaconda3/envs/tf-web/lib/python3.8/site-packages/keras/utils/traceback_utils.py", line 64, in error_handler
    return fn(*args, **kwargs)
  File "/home/melih/anaconda3/envs/tf-web/lib/python3.8/site-packages/keras/engine/training.py", line 1216, in fit
    tmp_logs = self.train_function(iterator)
  File "/home/melih/anaconda3/envs/tf-web/lib/python3.8/site-packages/tensorflow/python/util/traceback_utils.py", line 150, in error_handler
    return fn(*args, **kwargs)
  File "/home/melih/anaconda3/envs/tf-web/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py", line 910, in __call__
    result = self._call(*args, **kwds)
  File "/home/melih/anaconda3/envs/tf-web/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py", line 942, in _call
    return self._stateless_fn(*args, **kwds)  # pylint: disable=not-callable
  File "/home/melih/anaconda3/envs/tf-web/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 3130, in __call__
    return graph_function._call_flat(
  File "/home/melih/anaconda3/envs/tf-web/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 1959, in _call_flat
    return self._build_call_outputs(self._inference_function.call(
  File "/home/melih/anaconda3/envs/tf-web/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 598, in call
    outputs = execute.execute(
  File "/home/melih/anaconda3/envs/tf-web/lib/python3.8/site-packages/tensorflow/python/eager/execute.py", line 58, in quick_execute
    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
KeyboardInterrupt